language: scala
scala:
  - 2.11.6
node_js:
  - 0.10

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - "npm install -g gulp-cli"
  - "npm install -g karma"
  - "npm install"

script:
  - "sbt clean test"
  - "gulp test"
