language: scala
scala:
  - 2.11.6
node_js:
  - 0.10

# whitelist
branches:
  only:
    - master
    - develop

before_script:
  - "npm install -g gulp-cli"
  - "npm install -g karma"
  - "npm install"

script:
  - "sbt clean test"
  - "gulp test"
